variables:
  REPOSITORY_NAME: jtreiche/eim-2023-reservationapi
  IMAGE_TAG: reservation-api-$CI_COMMIT_SHORT_SHA


stages:
  - test
  - build
  - deploy


api-tests:
  stage: test
  image: python:3.8
  before_script:
    - pip install --no-cache-dir --upgrade --no-dependencies -r ./requirements.txt
    - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - postman login --with-api-key $POSTMAN_API_KEY
  script:
    - export USE_IN_MEMORY_DB=True
    - uvicorn src.main:app --host 0.0.0.0 --port 8000 &
    - sleep 10
    - postman collection run "25695533-4cbee508-f0d7-4837-9fae-626dfe89a66e"


build_image:
  stage: build
  image: docker@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90
  services:
    - docker:dind@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .
    - docker push $REPOSITORY_NAME:$IMAGE_TAG
  only:
    - main


deploy:
  stage: deploy
  before_script:
    - chmod 400 $WEBSERVER_SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $WEBSERVER_SSH_KEY $WEBSERVER_USER@$WEBSERVER_IP "
        sudo docker login -u $DOCKER_USER -p '$DOCKER_PASSWORD' &&
        sudo docker ps -aq | xargs -r sudo docker stop | xargs -r sudo docker rm &&
        sudo docker run -d
          -e DATABASE_DIALECT='$DATABASE_DIALECT'
          -e DATABASE_DRIVER='$DATABASE_DRIVER'
          -e DATABASE_USER='$DATABASE_USER'
          -e DATABASE_PASSWORD='$DATABASE_PASSWORD'
          -e DATABASE_HOST='$DATABASE_HOST'
          -e DATABASE_PORT='$DATABASE_PORT'
          -e DATABASE_NAME='$DATABASE_NAME'
          -e USE_IN_MEMORY_DB='$USE_IN_MEMORY_DB'
          -p 80:80 $REPOSITORY_NAME:$IMAGE_TAG"
  only:
    - main